{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "1c0b7b49",
   "metadata": {},
   "source": [
    "## Python Advance Assignment 7"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "b1a0c4af",
   "metadata": {},
   "source": [
    "#### Q1. What is the purpose of the try statement?"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "98390050",
   "metadata": {},
   "source": [
    "The purpose of the try statement in Python is to define a block of code where exceptional conditions or errors might occur. The try statement allows you to handle these exceptions gracefully by providing a mechanism for catching and handling them"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "71a1c01d",
   "metadata": {},
   "source": [
    "try:\n",
    "\n",
    "\n",
    "    # Code that may raise an exception\n",
    "    \n",
    "    \n",
    "except ExceptionType:\n",
    "    \n",
    "    \n",
    "    # Code to handle the exception\n",
    "    \n",
    "    \n",
    "Within the try block, you place the code that might raise an exception. If an exception occurs within the try block, it is caught by the corresponding except block. The except block specifies the type of exception to catch, and it contains the code that handles the exception.\n",
    "\n",
    "\n",
    "The try statement allows you to separate the normal flow of code from exceptional cases and provides a structured way to handle errors and exceptions."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "173da5fb",
   "metadata": {},
   "source": [
    "#### Q2. What are the two most popular try statement variations?"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "43515cd7",
   "metadata": {},
   "source": [
    "try-except statement: This variation is used to catch and handle specific exceptions. It allows you to specify the type of exception you want to catch, and if an exception of that type occurs, the corresponding except block is executed."
   ]
  },
  {
   "cell_type": "raw",
   "id": "24e40f24",
   "metadata": {},
   "source": [
    "try:\n",
    "    # Code that may raise an exception\n",
    "except ValueError:\n",
    "    # Handle ValueError\n",
    "except TypeError:\n",
    "    # Handle TypeError"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "9f92ad17",
   "metadata": {},
   "source": [
    "In this example, if a ValueError or TypeError exception occurs within the try block, the corresponding except block will be executed."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "37b67ded",
   "metadata": {},
   "source": [
    "try-except-else statement: This variation is used when you want to specify code that should be executed only if no exceptions are raised within the try block."
   ]
  },
  {
   "cell_type": "raw",
   "id": "5bbb1202",
   "metadata": {},
   "source": [
    "try:\n",
    "    # Code that may raise an exception\n",
    "except ExceptionType:\n",
    "    # Handle the exception\n",
    "else:\n",
    "    # Code to execute if no exception occurs"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "784e0e15",
   "metadata": {},
   "source": [
    "#### Q3. What is the purpose of the raise statement?"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "cccae0fe",
   "metadata": {},
   "source": [
    "The raise statement in Python is used to explicitly raise exceptions. It allows you to create and raise exceptions in your code, signaling that an exceptional condition or error has occurred."
   ]
  },
  {
   "cell_type": "raw",
   "id": "c89d7bb6",
   "metadata": {},
   "source": [
    "raise ExceptionType(\"Error message\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "2166e6ef",
   "metadata": {},
   "source": [
    "The raise statement is typically used when you encounter an exceptional situation that cannot be handled locally and needs to be propagated to an outer scope or caught by an exception handler. You can specify the type of exception to raise, such as ValueError, TypeError, or a custom exception class, along with an optional error message.\n",
    "\n",
    "\n",
    "By raising exceptions, you can signal errors or exceptional conditions, interrupt the normal flow of execution, and allow the exception to be caught and handled by appropriate exception handlers."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "0bb9a9d4",
   "metadata": {},
   "source": [
    "#### Q4. What does the assert statement do, and what other statement is it like?"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ed124263",
   "metadata": {},
   "source": [
    "The assert statement in Python is used as a debugging aid to verify that a given condition is true. It is primarily used for testing assumptions and catching potential bugs during development."
   ]
  },
  {
   "cell_type": "raw",
   "id": "43e50051",
   "metadata": {},
   "source": [
    "assert condition, \"Optional error message\""
   ]
  },
  {
   "cell_type": "markdown",
   "id": "8ba40595",
   "metadata": {},
   "source": [
    "The condition is an expression that is expected to be true. If the condition evaluates to False, the assert statement raises an AssertionError exception, optionally displaying the specified error message.\n",
    "\n",
    "\n",
    "The assert statement is similar to the if statement, but with a focus on catching logical errors and inconsistencies in the code rather than controlling program flow. It helps developers identify incorrect assumptions and validate expected conditions at runtime."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "287bedfa",
   "metadata": {},
   "source": [
    "#### Q5. What is the purpose of the with/as argument, and what other statement is it like?"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ceb2ce50",
   "metadata": {},
   "source": [
    "The with/as statement in Python is used for resource management and ensures that a specific block of code is executed in the context of a context manager. The purpose of the with/as argument is to simplify the acquisition and release of resources, such as opening and closing files or database connections, in a safe and concise manner."
   ]
  },
  {
   "cell_type": "raw",
   "id": "88815110",
   "metadata": {},
   "source": [
    "with expression as variable:\n",
    "    # Code that uses the resource"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a7be09ee",
   "metadata": {},
   "source": [
    "The expression represents a context manager object, which is an object that defines the methods __enter__() and __exit__(). The __enter__() method sets up the resource, and the __exit__() method handles resource cleanup.\n",
    "\n",
    "\n",
    "When the with block is entered, the __enter__() method of the context manager is called, and it returns an object that is assigned to the variable. The block of code within the with statement can then use the resource accessed through the variable. After the block of code completes or an exception is raised, the __exit__() method of the context manager is called to clean up the resource.\n",
    "\n",
    "\n",
    "The with/as statement is similar to the try/finally statement in terms of resource management. However, the with/as statement provides a more readable and concise syntax for managing resources by encapsulating the setup and cleanup logic within the context manager object."
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
